In [83]:
# Import numpy module
import numpy as np

In [84]:
my_list = [1,2,3]

In [85]:
# Convert normal python list object to numpy array object
arr = np.array(my_list)

In [86]:
arr

array([1, 2, 3])

In [87]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [88]:
# Convert list of lists to numpy matrix
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [89]:
# arange
# Create a numpy array of all the integers between a number and another number
# optionally you can state the steps
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [90]:
# zeros
# Create a list of zeros
np.zeros(3)

array([0., 0., 0.])

In [91]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [92]:
# ones
# Create a list of ones
np.ones(4)

array([1., 1., 1., 1.])

In [93]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [94]:
# linspace
# Create the total possible series between a particular range
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [95]:
# eye
# Create an identity matrix 
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [96]:
# random.rand
# Create a list of random numbers
np.random.rand(5)

array([0.52095107, 0.47632613, 0.24238923, 0.3154702 , 0.42572823])

In [97]:
# random.randn
# Create a list of random lists
np.random.randn(4,4)

array([[ 0.52797443,  0.36703864,  0.26119036, -0.02096235],
       [-1.6607148 ,  1.1575081 , -1.2630807 ,  0.46715593],
       [-0.50739649,  1.9105013 ,  0.76095414,  0.09488462],
       [ 0.73503442, -0.03638481,  0.28665248,  0.05014305]])

In [98]:
# random.randint
# Create a list of rand integers and state the steps
np.random.randint(1,100,10)

array([19, 63, 67, 63, 12,  4, 44, 91, 72, 61])

In [99]:
arr = np.arange(25)

In [100]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [101]:
ranarr = np.random.randint(0,50,10)

In [102]:
ranarr

array([21, 13, 14, 10, 25, 46, 39, 47,  1, 20])

In [103]:
# reshape
# Reshape the matrix to a desired number of rows and columns
arr = arr.reshape(5,5)

In [104]:
# max
# get the max value in a list
ranarr.max()

47

In [105]:
# min
# get the min value in a list
ranarr.min()

1

In [106]:
# argmax
# get the position of the max
ranarr.argmax()

7

In [108]:
# shape
# get the matrix shape
arr.shape

(5, 5)

In [109]:
arr.dtype

dtype('int32')