In [1]:
#Numpy Indexing and Selection

In [2]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[8]

8

In [10]:
new_arr = arr[1:5]

In [12]:
new_arr[:] = 100

In [13]:
new_arr

array([100, 100, 100, 100])

In [14]:
arr

array([  0, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])