In [1]:
#Numpy Exercises Overview

Import NumPy as np

In [3]:
import numpy as np

Create an array of 10 zeros

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Create an array of 10 ones

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Create an array of 10 fives

In [7]:
np.array(5)

array(5)

Create an array of the integers from 10 to 50

In [9]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

Create an array of all even integers from 10 to 50

In [12]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

Create a 3x3 matrix with values ranging from 0 to 8

In [13]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Create a 3x3 identity matrix

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Use NumPy to generate a random number between 0 and 1

In [21]:
np.random.rand()

0.2061677549266574

Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [25]:
np.random.randn(25)

array([-0.80300893,  0.51249988, -0.44600557,  1.17075641,  2.38783096,
       -1.12716341,  0.54633076,  0.75860794,  0.92549758, -0.52778055,
       -1.47943884, -0.09962569,  0.23399226,  0.66649445, -2.07757125,
       -0.72185856,  0.41965262,  0.2200338 ,  0.55560438,  0.39672509,
        0.91370282,  0.45991765, -0.69448654, -0.61165037, -1.17269466])

Create the following matrix

In [35]:
np.linspace(0.0,1.0).reshape(10,5)

array([[0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265],
       [0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347],
       [0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429],
       [0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ],
       [0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592],
       [0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673],
       [0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755],
       [0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837],
       [0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918],
       [0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ]])

Create an array of 20 linearly spaced points between 0 and 1

In [36]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## NumPy indexing and selection

In [38]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [39]:
# Write code her that reproduces the output of the cell below

In [41]:
mat[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [42]:
mat[3,4]

20

In [48]:
mat[:3, 1:2]

array([[ 2],
       [ 7],
       [12]])

In [49]:
mat[4]

array([21, 22, 23, 24, 25])

In [51]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [52]:
np.sum(mat)

325

In [66]:
np.sum(np.arange(55,76, 5))

325

In [ ]:
np.sum(np.array([55,60,]))