In [20]:
#Numpy indexing and selection 2

In [21]:
import numpy as np

In [22]:
arr_2d = np.array([[5,10,15], [20, 25,30], [35,40,45]])

In [23]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [24]:
# Double bracket indexing
arr_2d[0][0]

5

In [25]:
# Single bracket indexing
arr_2d[0,2]

15

In [26]:
# Indexing slicing, selecting mutliple subsets
arr_2d[1:3,1:]

array([[25, 30],
       [40, 45]])

In [27]:
arr = np.arange(1,11)

In [51]:
# Conditional selection
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
bool_arr = arr >= 5

In [53]:
# Index where condition is true 
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [54]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [55]:
arr[arr >= 5]

array([ 5,  6,  7,  8,  9, 10])

In [58]:
arr[arr<3]

array([1, 2])

In [99]:
new_arr = np.random.randn(20)

In [100]:
new_arr

array([-0.02207849,  0.36440281,  0.86459492,  1.53220331, -1.69469128,
       -1.43594185, -0.29235515, -0.92725562, -0.02794982, -0.73290491,
       -0.97631861, -0.89690692, -0.05092015, -0.72743364,  0.23444249,
        0.85644523, -0.67344239,  1.48780891,  0.1650761 , -0.96788459])

In [101]:
new_arr[new_arr>1] = 1
new_arr[new_arr<1] = 0

In [102]:
new_arr.reshape(4,5)

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [103]:
new_arr.flatten()

array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0.])